apiVersion: v1
kind: Service
metadata: 
  name: frontend
<<<<<<< HEAD
  namespace: k8s-noufa
=======
  namespace: three-tier
>>>>>>> 6b649c652bfd80d29a2015ee5471aab600141031
spec:
  ports:
  - port: 3000
    protocol: TCP
  type: ClusterIP
  selector:
    role: frontend