apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-volume-claim
<<<<<<< HEAD
  namespace: k8s-noufa
=======
  namespace: three-tier
>>>>>>> 6b649c652bfd80d29a2015ee5471aab600141031
spec: 
  accessModes:  
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
